version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pdadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=omar@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin

    ports:
      - "80:80"
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"


